### ISSUE TITLE
3D infinite square well

### ISSUE THREAD

**Issue by ajarifi** [ohno/Antique.jl#41] opened 2024-04-09 00:16 UTC
I think this potential is simple and has an analytic solution.

**Comment by lhapp27** [comment] 2024-04-19 04:29
I can implement this module. The other models in the open issues seem to require numeric solutions.

**Comment by ohno** [comment] 2024-04-19 05:07
This is a good first issue (development practice). I would like to save it for the main force developers of Antique.jl v2.0.0. I want you to work on challenging issues if you haven't started developing yet.

The purpose of this package is to provide a benchmark for numerical calculations. There is no problem even if it is not a "pure analytical" solution, as long as it is "almost analytical". The problem is that it will take more time, but I will support you.

How about the model below?
- ground state of https://github.com/ohno/Antique.jl/issues/35 (a good benchmark of three-body calculation)
- https://github.com/ohno/Antique.jl/issues/1 (generalization of Pöschl-Teller potential)
- finite well potential (a good example of almost analytical solutions)
- https://github.com/ohno/Antique.jl/issues/17 (a good example of almost analytical solutions)

**Comment by ajarifi** [comment] 2024-04-23 12:06
I believe that various potentials can be applied to general 1D, 2D, and 3D problems, including potential wells and their symmetries such as spherical, cylindrical, etc. Perhaps it is interesting to consider.

**Comment by ohno** [comment] 2024-05-10 10:13
This issue is closed by  https://github.com/ohno/Antique.jl/commit/a9068d5c6913637b57a59340cc3938b538c0c5c5 and https://github.com/ohno/Antique.jl/commit/57c6ee8cf3d2a47e773130b3ade4f0230614f850

**Closed by ohno** 2024-05-10 10:13 UTC
Labels: good first issue, new model
